apiVersion: v1
kind: Service
metadata:
  name: testapp-service
spec:
  selector:
    app: testapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      name: 5000-3000
  type: ClusterIP
status: 
  loadBalancer: {}