apiVersion: v1
kind: Service
metadata:
  name: testapp-service-nodeport
spec:
  selector:
    app: testapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      name: 5000-3000
  type: NodePort
status: 
  loadBalancer: {}